/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef PDFSIGANGMASS
#define PDFSIGANGMASS

#include <math.h>
#include "Math/SpecFunc.h"
#include "TMath.h"

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooRealVar.h"
#include "RooCategoryProxy.h"
#include "RooSetProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include "RooFit.h"
#include "Riostream.h"
#include "RooObjCacheManager.h"
 
class PdfSigAngMass : public RooAbsPdf {
 protected:

  RooRealProxy ctK ;
  RooRealProxy ctL ;
  RooRealProxy phi ;
  RooRealProxy m ;
  RooRealProxy Fl ;
  RooRealProxy P1 ;
  RooRealProxy P2 ;
  RooRealProxy P3 ;
  RooRealProxy P4p ;
  RooRealProxy P5p ;
  RooRealProxy P6p ;
  RooRealProxy P8p ;
  RooRealProxy mFrac ;

  RooRealProxy EffC ;
  RooRealProxy EffW ;

  std::vector<double> intCPart;
  std::vector<double> intWPart;

  RooRealProxy PenTerm;
  RooRealProxy rtMassTerm;
  RooRealProxy wtMassTerm;
  
//   RooSetProxy setProxy;

  bool isPenalised;
  
  const RooAbsReal* effCVal() const { 
    // Return pointer to efficiency function in product
    return (RooAbsReal*) EffC.absArg() ; 
  }

  const RooAbsReal* effWVal() const { 
    // Return pointer to efficiency function in product
    return (RooAbsReal*) EffW.absArg() ; 
  }

  const RooAbsReal* penTermVal() const {
    // Return pointer to penalty term function
    return (RooAbsReal*) PenTerm.absArg() ;
  }
  const RooAbsReal* rtMassTermVal() const {
    // Return pointer to mass term function for RT
    return (RooAbsReal*) rtMassTerm.absArg() ;
  }
  const RooAbsPdf* rtMassTermPdf() const {
    // Return pointer to mass term function for RT
    RooAbsArg* absArg = rtMassTerm.absArg();
    RooAbsPdf* pdf = dynamic_cast<RooAbsPdf*>(absArg);    
    return pdf ;
  }
  const RooAbsReal* wtMassTermVal() const {
    // Return pointer to mass term function for RT
    return (RooAbsReal*) wtMassTerm.absArg() ;
  }

  Double_t evaluate() const ;

 public:
  PdfSigAngMass() {} ; 
  PdfSigAngMass(const char *name, const char *title,
	    RooAbsReal& _ctK,
	    RooAbsReal& _ctL,
	    RooAbsReal& _phi,
	    RooAbsReal& _m,
	    RooAbsReal& _Fl,
	    RooAbsReal& _P1,
	    RooAbsReal& _P2,
	    RooAbsReal& _P3,
	    RooAbsReal& _P4p,
	    RooAbsReal& _P5p,
	    RooAbsReal& _P6p,
	    RooAbsReal& _P8p,
// 	    RooAbsReal& _mean,
// 	    RooAbsReal& _sigma,
	    RooAbsReal& _mFrac,
	    RooAbsReal& _EffC,
	    RooAbsReal& _EffW,
	    std::vector<double> _intCPart,
	    std::vector<double> _intWPart,
	    RooAbsReal& _PenTerm,
	    RooAbsReal& _wtMassTerm,
	    RooAbsReal& _rtMassTerm//,
// 	    RooSetProxy& _setProxy
	    );
  PdfSigAngMass(const char *name, const char *title,
	    RooAbsReal& _ctK,
	    RooAbsReal& _ctL,
	    RooAbsReal& _phi,
	    RooAbsReal& _m,
	    RooAbsReal& _Fl,
	    RooAbsReal& _P1,
	    RooAbsReal& _P2,
	    RooAbsReal& _P3,
	    RooAbsReal& _P4p,
	    RooAbsReal& _P5p,
	    RooAbsReal& _P6p,
	    RooAbsReal& _P8p,
// 	    RooAbsReal& _mean,
// 	    RooAbsReal& _sigma,
	    RooAbsReal& _mFrac,
	    RooAbsReal& _EffC,
	    RooAbsReal& _EffW,
	    std::vector<double> _intCPart,
	    std::vector<double> _intWPart,
	    RooAbsReal& _rtMassTerm, 
	    RooAbsReal& _wtMassTerm//,
// 	    RooSetProxy& _setProxy
	    );
  PdfSigAngMass(const PdfSigAngMass& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PdfSigAngMass(*this,newname); }
  inline virtual ~PdfSigAngMass() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

  ClassDef(PdfSigAngMass,1) // PDF for (angular decay rate x efficiency) of both correctly-tagged and wrongly-tagged events
    };
 
#endif
